"""empty message

Revision ID: 0d7a01991fcc
Revises: e6128acec9a6
Create Date: 2022-08-23 10:49:19.749647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7a01991fcc'
down_revision = 'e6128acec9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deporte', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.Integer(), nullable=True),
    sa.Column('duraciónevento', sa.Integer(), nullable=True),
    sa.Column('edadminima', sa.Integer(), nullable=True),
    sa.Column('edadmáxima', sa.Integer(), nullable=True),
    sa.Column('opciónpago', sa.Boolean(), nullable=False),
    sa.Column('airelibrecubierto', sa.Boolean(), nullable=False),
    sa.Column('Lugarprovincia', sa.String(length=250), nullable=True),
    sa.Column('lugarciudad', sa.String(length=250), nullable=True),
    sa.Column('direcionevento', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usereventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idusuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'username')
    op.drop_column('user', 'age')
    op.drop_table('usereventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
