"""empty message

Revision ID: 17d7839dd8de
Revises: 750c8627818e
Create Date: 2022-09-02 13:51:32.531344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d7839dd8de'
down_revision = '750c8627818e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'ciudad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('ciudad', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
