"""empty message

Revision ID: 2dff904d0349
Revises: 545e90a910ff
Create Date: 2022-08-26 04:30:45.751411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dff904d0349'
down_revision = '545e90a910ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usereventos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usereventos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idusuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('idevento', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idevento'], ['eventos.id'], name='usereventos_idevento_fkey'),
    sa.ForeignKeyConstraint(['idusuario'], ['user.id'], name='usereventos_idusuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='usereventos_pkey')
    )
    # ### end Alembic commands ###
