"""empty message

Revision ID: 497f1262236e
Revises: 2dff904d0349
Create Date: 2022-08-26 19:00:11.852643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497f1262236e'
down_revision = '2dff904d0349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=250), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('agemin', sa.Integer(), nullable=True),
    sa.Column('agemax', sa.Integer(), nullable=True),
    sa.Column('payment', sa.Integer(), nullable=False),
    sa.Column('space', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'evento_id')
    )
    op.drop_table('eventos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sport', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agemin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agemax', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('space', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='eventos_pkey')
    )
    op.drop_table('participant')
    op.drop_table('evento')
    # ### end Alembic commands ###
