"""empty message

Revision ID: 545e90a910ff
Revises: 0d7a01991fcc
Create Date: 2022-08-24 00:00:36.588505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545e90a910ff'
down_revision = '0d7a01991fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('sport', sa.String(length=250), nullable=True))
    op.add_column('eventos', sa.Column('date', sa.Integer(), nullable=True))
    op.add_column('eventos', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('eventos', sa.Column('agemin', sa.Integer(), nullable=True))
    op.add_column('eventos', sa.Column('agemax', sa.Integer(), nullable=True))
    op.add_column('eventos', sa.Column('payment', sa.Integer(), nullable=False))
    op.add_column('eventos', sa.Column('space', sa.Boolean(), nullable=False))
    op.drop_column('eventos', 'edadminima')
    op.drop_column('eventos', 'Lugarprovincia')
    op.drop_column('eventos', 'airelibrecubierto')
    op.drop_column('eventos', 'opciónpago')
    op.drop_column('eventos', 'edadmáxima')
    op.drop_column('eventos', 'deporte')
    op.drop_column('eventos', 'duraciónevento')
    op.drop_column('eventos', 'fecha')
    op.drop_column('eventos', 'lugarciudad')
    op.drop_column('eventos', 'direcionevento')
    op.add_column('user', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['username'])
    op.add_column('usereventos', sa.Column('idevento', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usereventos', 'eventos', ['idevento'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usereventos', type_='foreignkey')
    op.drop_column('usereventos', 'idevento')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('user', 'description')
    op.add_column('eventos', sa.Column('direcionevento', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('lugarciudad', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('fecha', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('duraciónevento', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('deporte', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('edadmáxima', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('opciónpago', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('eventos', sa.Column('airelibrecubierto', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('eventos', sa.Column('Lugarprovincia', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('edadminima', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('eventos', 'space')
    op.drop_column('eventos', 'payment')
    op.drop_column('eventos', 'agemax')
    op.drop_column('eventos', 'agemin')
    op.drop_column('eventos', 'duration')
    op.drop_column('eventos', 'date')
    op.drop_column('eventos', 'sport')
    # ### end Alembic commands ###
