"""empty message

Revision ID: 703d76cdbf7c
Revises: 17d7839dd8de
Create Date: 2022-09-02 13:56:37.481814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703d76cdbf7c'
down_revision = '17d7839dd8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('ciudad', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'ciudad')
    # ### end Alembic commands ###
