"""empty message

Revision ID: 750c8627818e
Revises: 866649d050b7
Create Date: 2022-09-02 13:45:56.131266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750c8627818e'
down_revision = '866649d050b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('ciudad', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'ciudad')
    # ### end Alembic commands ###
