"""empty message

Revision ID: 866649d050b7
Revises: b4d1f14be66f
Create Date: 2022-08-29 16:57:05.685988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866649d050b7'
down_revision = 'b4d1f14be66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('description', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'description')
    # ### end Alembic commands ###
