"""empty message

Revision ID: b4d1f14be66f
Revises: 1b39d3bf4c5a
Create Date: 2022-08-29 16:50:07.802460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d1f14be66f'
down_revision = '1b39d3bf4c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('participantmax', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'participantmax')
    # ### end Alembic commands ###
