"""empty message

Revision ID: c759794e08d4
Revises: fe5f6888e867
Create Date: 2022-08-31 19:36:47.835448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c759794e08d4'
down_revision = 'fe5f6888e867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('description', sa.String(length=250), nullable=True))
    op.add_column('evento', sa.Column('localization', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'localization')
    op.drop_column('evento', 'description')
    # ### end Alembic commands ###
