"""empty message

Revision ID: fa542a56d2e8
Revises: c759794e08d4
Create Date: 2022-09-02 18:01:42.227719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa542a56d2e8'
down_revision = 'c759794e08d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('participantmax', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'participantmax')
    # ### end Alembic commands ###
